const accountId = 379;
let acountEmail = "sartaj@gamil.com";
var accountPassword = "98765";
let accountCity = " Bettiah";
accountEmail = "raj@gmail.com";
let nameId = "sartaj";
console.log(accountId);
let accountState;
console.table([accountId,nameId,accountPassword,accountCity,accountState]);
console.log(acountEmail);